# Generated by Django 4.0.1 on 2022-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_auth', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploreuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
