# Generated by Django 4.0.1 on 2022-04-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_auth', '0004_exploreuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploreuser',
            name='is_active',
        ),
    ]
