# Generated by Django 4.0.1 on 2022-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_auth', '0005_remove_exploreuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploreuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
