# Generated by Django 4.0.1 on 2022-03-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
